dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/dog
  name: dog
  num_workers: 4
  root_dir: /mnt/data/dataset/fgvc_datasets/datasets/Stanford_Dog/Images
  transformer:
    auto_aug: null
    image_size: 224
    rand_erase: 0.0
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_swin_base_p4_w7_in21k
  name: swin_base_p4_w7_in21k_dog_224_123
  seed: 123
  use_amp: false
model:
  name: Swin_Base_P4_W7_IN21K
  num_classes: 120
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 0.001
    momentum: 0.9
    name: Adam
    weight_decay: 0.0001
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
