dataset:
  batch_size: 32
  meta_dir: /media/Dormammu/haoc/hawkeye_fgvc/metadata/car
  name: car
  num_workers: 4
  root_dir: /media/Auriga/datasets/Stanford_Car/
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.2256590393747257
    resize_size: 256
experiment:
  log_dir: /media/Dormammu/haoc/hawkeye_fgvc/results/base_res50_tune
  name: ResNet50_Cars_224_None
  seed: 42
  tune: true
  use_amp: false
model:
  name: ResNet50
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 0.00011428752369187993
    momentum: 0.9
    name: Adam
    weight_decay: 0.015228694974175724
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
