dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/cub
  name: cub
  num_workers: 4
  root_dir: /media/Zeus/datasets/CUB_200_2011/CUB_200_2011/images
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.2
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_res50_tune
  name: ResNet50_CUB200_224
  seed: 42
  tune: true
  use_amp: false
model:
  name: ResNet50
  num_classes: 200
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 0.0001
    momentum: 0.9
    name: Adam
    weight_decay: 0.002
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
