dataset:
  batch_size: 32
  meta_dir: /media/Dormammu/haoc/hawkeye_fgvc/metadata/dog
  name: car
  num_workers: 4
  root_dir: /media/Auriga/datasets/Stanford_Dog/Images
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.026424995501243394
    resize_size: 256
experiment:
  log_dir: /media/Dormammu/haoc/hawkeye_fgvc/results/base_res50_tune
  name: ResNet50_Dogs_224_None
  seed: 42
  tune: true
  use_amp: false
model:
  name: ResNet50
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 1.0043747937032744e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.001543263595937155
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
