dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/web_car
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/web-car
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.10511145287395077
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_res50
  name: ResNet50_WebCar_224
  seed: 42
  tune: true
  use_amp: false
model:
  name: ResNet50
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 7.75474395063335e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.030195540342182862
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
