dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/web_aircraft
  name: cub
  num_workers: 4
  root_dir: /media/Zeus/datasets/web-aircraft
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.04794543020980112
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_res50
  name: ResNet50_WebAircraft_224
  seed: 42
  use_amp: false
model:
  name: ResNet50
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 8.670198627517481e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.00010139911437301347
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
