dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/aircraft
  name: aircraft
  num_workers: 4
  root_dir: /mnt/data/dataset/fgvc_datasets/datasets/fgvc-aircraft-2013b/data/images
  transformer:
    auto_aug: rand_aug
    image_size: 224
    rand_erase: 0.0687
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_transfg_vit_base_p16_in21k
  name: transfg_vit_base_p16_in21k_aircraft_224_7
  seed: 7
  use_amp: false
model:
  name: TransFG_ViT_Base_P16_IN21K
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 2.1e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.017445
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
trainer:
  name: Baseline
