dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/aircraft
  name: aircraft
  num_workers: 4
  root_dir: /media/Zeus/datasets/fgvc-aircraft-2013b/data/images
  transformer:
    auto_aug: null
    image_size: 224
    rand_erase: 0.0
    resize_size: 256
experiment:
  log_dir: ./results/pim_swin_tiny_p4_w7_in21k
  name: swin_tiny_p4_w7_in21k_aircraft_224_123
  seed: 123
  use_amp: false
model:
  backbone_name: Swin_Tiny_P4_W7_IN21K
  name: PIM
  num_classes: 100
  pim:
    fpn_size: 1536
    lambda_b: 0.5
    lambda_c: 1.0
    lambda_n: 5.0
    lambda_s: 0.0
    num_selects:
      layer1: 256
      layer2: 128
      layer3: 32
      layer4: 32
    proj_type: Linear
    upsample_type: Conv
    use_combiner: true
    use_fpn: true
    use_selection: true
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 0.001
    momentum: 0.9
    name: Adam
    weight_decay: 0.0001
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
trainer:
  name: PIM
