dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_aircraft
  name: web_aircraft
  num_workers: 4
  root_dir: /mnt/data/dataset/fgvc_datasets/datasets/web_aircraft
  transformer:
    auto_aug: rand_aug
    image_size: 224
    rand_erase: 0.1474
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_vit_small_p16
  name: vit_small_p16_web_aircraft_224_123
  seed: 123
  use_amp: false
model:
  name: ViT_Small_P16
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 5.0e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.009283
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
trainer:
  name: Baseline
