dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_car
  name: web_car
  num_workers: 4
  root_dir: /mnt/default/datasets/hawkeye_datasets/datasets/web_car
  transformer:
    auto_aug: rand_aug
    image_size: 224
    rand_erase: 0.17737137898770733
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/hawkeye_fgvc_2023/v1/baseline_vit_small_p16
  name: vit_small_p16_web_car_224
  seed: 0
  use_amp: false
model:
  name: ViT_Small_P16
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 4.141006420617345e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.0001443726221382986
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
