dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/car
  name: car
  num_workers: 4
  root_dir: /mnt/default/datasets/fgvc_datasets/datasets/Stanford_Car
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.1052
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_vit_small_p16
  name: vit_small_p16_car_224_42
  seed: 42
  use_amp: false
model:
  name: ViT_Small_P16
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 7.0e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.030771
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
