description: baseline_resnet50_in21k_224 tune tasks
target:
 service: sing
 name: msrresrchvc
 workspace_name: msrresrchws
environment:
 image:  amlt-sing/pytorch-1.8.0
 setup:
  - python -m pip install -U pip
  - pip install pyyaml
  - pip install -U "ray[default]"
  - pip install tensorboard
  - pip install -U scikit-learn
  - pip install matplotlib
  - pip install progress
  - pip install pandas
  - pip install tensorboardx
  - pip install tqdm
  - pip install yacs
  - python -m pip install -U scikit-image
  - pip install timm
  - pip install tqdm
  - pip install --upgrade ruamel.yaml --ignore-installed ruamel.yaml 
  - pip install --upgrade torchvision 
  - pip install hyperopt
  - pip install 'protobuf<=3.20.1' --force-reinstall
  - pwd 

code:
 local_dir: ./
storage:
 hawkeye_fgvc:
  storage_account_name: transferlearningdrive
  container_name: teamdrive
  is_output: True
jobs:
- name: baseline_resnet50_in21k_224_aircraft
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_aircraft_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_aircraft_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_aircraft_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_car
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_car_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_car_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_car_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_cub
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_cub_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_cub_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_cub_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_dog
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_dog_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_dog_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_dog_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_web_aircraft
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_aircraft_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_aircraft_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_aircraft_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_web_bird
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_bird_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_bird_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_bird_224_b32_seed7.yaml

- name: baseline_resnet50_in21k_224_web_car
  sku: NCv2:16G1-P100
  sla_tier: premium
  command:
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_car_224_b32_seed123.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_car_224_b32_seed42.yaml
  - python train.py --config /tmp/code/configs/baseline_resnet50_in21k_224/baseline_resnet50_in21k_web_car_224_b32_seed7.yaml

