dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_aircraft
  name: web_aircraft
  num_workers: 4
  root_dir: /mnt/default/datasets/hawkeye_datasets/datasets/web_aircraft
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.055991055705633896
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/hawkeye_fgvc_2023/v1/baseline_resnet50
  name: resnet50_web_aircraft_224
  seed: 0
  use_amp: false
model:
  name: ResNet50
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 0.00011006902918066039
    momentum: 0.9
    name: Adam
    weight_decay: 0.004695803870704579
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
