dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/dog
  name: dog
  num_workers: 4
  root_dir: /mnt/default/dataset/fgvc_datasets/datasets/Stanford_Dog/Images
  transformer:
    auto_aug: null
    image_size: 224
    rand_erase: 0.1701
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_resnet50
  name: resnet50_dog_224_7
  seed: 7
  use_amp: false
model:
  name: ResNet50
  num_classes: 120
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 1.1e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.005111
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
