dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_bird
  name: web_bird
  num_workers: 4
  root_dir: /mnt/default/datasets/hawkeye_datasets/datasets/web_bird
  transformer:
    auto_aug: null
    image_size: 224
    rand_erase: 0.02045132361634866
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/hawkeye_fgvc_2023/v1/baseline_resnet50
  name: resnet50_web_bird_224
  seed: 0
  use_amp: false
model:
  name: ResNet50
  num_classes: 200
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 2.4713792065377816e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.0054369964830616605
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
