dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/car
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/Stanford_Car/
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.14
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_res50_in21k
  name: ResNet50_IN21K_Cars_224
  seed: 42
  tune: true
  use_amp: false
model:
  name: ResNet50_IN21K
  num_classes: 196
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 0.001
    momentum: 0.9
    name: Adam
    weight_decay: 0.0027
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
