dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/web_aircraft
  name: aircraft
  num_workers: 4
  root_dir: /media/Zeus/datasets/web-aircraft
  transformer:
    auto_aug: rand_aug
    image_size: 224
    rand_erase: 0.14
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_res50_in21k
  name: ResNet50_IN21K_WebAircraft_224
  seed: 42
  use_amp: false
model:
  name: ResNet50_IN21K
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 0.0004
    momentum: 0.9
    name: Adam
    weight_decay: 0.0025
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
