dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_car
  name: web_car
  num_workers: 4
  root_dir: /mnt/data/dataset/fgvc_datasets/datasets/web_car
  transformer:
    auto_aug: auto_aug
    image_size: 224
    rand_erase: 0.1973
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/pim_swin_base_p4_w7_in21k
  name: swin_base_p4_w7_in21k_web_car_224_42
  seed: 42
  use_amp: false
model:
  backbone_name: Swin_Base_P4_W7_IN21K
  name: PIM
  num_classes: 196
  pim:
    fpn_size: 1536
    lambda_b: 0.5
    lambda_c: 1.0
    lambda_n: 5.0
    lambda_s: 0.0
    num_selects:
      layer1: 256
      layer2: 128
      layer3: 32
      layer4: 32
    proj_type: Linear
    upsample_type: Conv
    use_combiner: true
    use_fpn: true
    use_selection: true
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 2.2e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.001443
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
trainer:
  name: PIM
