dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/web_aircraft
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/web-aircraft
  transformer:
    auto_aug: rand_aug
    image_size: 224
    rand_erase: 0.04
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_vit_base_in21k
  name: ViT_Base_IN21K_WebAircraft_224
  seed: 42
  use_amp: false
model:
  name: ViT_Base_P16_IN21K
  num_classes: 100
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 7.75e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.004
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
