dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/cub
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/CUB_200_2011/CUB_200_2011/images
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.1450112978330128
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_vit_base_in21k
  name: ViT_Base_IN21K_CUB200_224
  seed: 42
  use_amp: false
model:
  name: ViT_Base_P16_IN21K
  num_classes: 200
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 4.390311377984881e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.00011657813402534243
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
