dataset:
  batch_size: 32
  meta_dir: /media/Zeus/hawkeye_fgvc/metadata/web_bird
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/web-bird
  transformer:
    auto_aug: null
    image_size: 224
    rand_erase: 0.08430359494142395
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_vit_base_in21k
  name: ViT_Base_IN21K_WebBird_224
  seed: 42
  use_amp: false
model:
  name: ViT_Base_P16_IN21K
  num_classes: 200
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 1.4838741245089584e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.004532685133618085
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
