dataset:
  batch_size: 32
  meta_dir: /media/Zeus//hawkeye_fgvc/metadata/dog
  name: car
  num_workers: 4
  root_dir: /media/Zeus/datasets/Stanford_Dog/Images
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.1582919985956636
    resize_size: 256
experiment:
  log_dir: /media/Zeus/hawkeye_fgvc/results/base_vit_base_in21k
  name: ViT_Base_IN21K_Dogs_224
  seed: 42
  use_amp: false
model:
  name: ViT_Base_P16_IN21K
  num_classes: 120
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 30
  optimizer:
    clip_grad: null
    lr: 1.7245769006895233e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.029186997324348502
  save_frequence: 30
  scheduler:
    T_max: 30
    eta_min: 1.0e-05
    name: CosineAnnealingLR
