dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/web_bird
  name: web_bird
  num_workers: 4
  root_dir: /mnt/default/dataset/fgvc_datasets/datasets/web_bird
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.2
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/fgvc_2023/v1/baseline_resnet50_in21k
  name: resnet50_in21k_web_bird_224_123
  seed: 123
  use_amp: false
model:
  name: ResNet50_IN21K
  num_classes: 200
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 0.0001
    momentum: 0.9
    name: Adam
    weight_decay: 0.002
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
