dataset:
  batch_size: 32
  meta_dir: /tmp/code/metadata/dog
  name: dog
  num_workers: 4
  root_dir: /mnt/default/datasets/hawkeye_datasets/datasets/Stanford_Dog/Images
  transformer:
    auto_aug: ta_wide
    image_size: 224
    rand_erase: 0.0991336172864091
    resize_size: 256
experiment:
  log_dir: /mnt/default/projects/hawkeye_fgvc_2023/v1/baseline_resnet50_in21k
  name: resnet50_in21k_dog_224
  seed: 0
  use_amp: false
model:
  name: ResNet50_IN21K
  num_classes: 120
train:
  criterion:
    name: CrossEntropyLoss
  epoch: 50
  optimizer:
    clip_grad: null
    lr: 5.04662662818074e-05
    momentum: 0.9
    name: Adam
    weight_decay: 0.0019299479156129418
  save_frequence: 50
  scheduler:
    T_max: 50
    eta_min: 1.0e-08
    name: CosineAnnealingLR
